### PR TITLE
feat: added in vault charts as cluster pre-req

### PR DESCRIPTION
**Pull request by chrismellard**

### CODE REVIEW

**Comment by jstrachan** [comment]
PR fails with:
```
  on ../../modules/vault/charts.tf line 1, in resource "helm_release" "vault-operator":
   1: resource "helm_release" "vault-operator" {

}
    apply.go:15:
        	Error Trace:	apply.go:15
        	            				terraform_eks_test.go:31
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1;
        	            	Error: Kubernetes cluster unreachable: stat /tekton/home/.kube/config: no such file or directory

        	            	  on ../../modules/vault/charts.tf line 1, in resource "helm_release" "vault-operator":
        	            	   1: resource "helm_release" "vault-operator" {

        	            	}
```

**Comment by dicolasi** [comment]
tried this manually in 2 clusters. Everything works fine.

**Comment by marsdalesa** [comment]
@jstrachan @chrismellard  with this change, wouldn't https://github.com/jx3-gitops-repositories/jx3-eks-vault/blob/master/helmfiles/secret-infra/helmfile.yaml need to be updated to remove the vault charts?

**Comment by jstrachan** [comment]
until we figure out the way to get the BDD tests working again with this change I'm gonna go ahead and merge this

**Comment by jstrachan** [comment]
@marsdalesa those vault charts are now removed: https://github.com/jx3-gitops-repositories/jx3-eks-vault/blob/master/helmfiles/secret-infra/helmfile.yaml

**Pull request merged**
