### PR TITLE
chore: Switch to Lighthouse as default webhook provider

### PR DESCRIPTION
**Pull request by abayer**

### CODE REVIEW

**Comment by abayer** [comment]
@hferentschik The test seems to be failing with
```
Error: Error attaching policy arn:aws:iam::296178596335:policy/vault_us-east-1-2020050616512586470000000c to IAM User **-bdd-test: LimitExceeded: Cannot exceed quota for PoliciesPerUser: 10
	status code: 409, request id: 53cf51d8-3234-47b7-90bd-f75efe7daa76
```

I have no idea what all is involved in that. =)

**Comment by hferentschik** [comment]
@abayer there is a quota we keep exceeding and atm we need to manually clean up. TBH, I am not quite sure why this does not get cleaned up. @dgozalo knows more about it. Somehow we need a way to better handle this. 

@dgozalo any idea? Are these policies not created by Terraform? And if so, why are they not deleted on a destroy?

**Pull request merged**
