### PR TITLE
fix: invalid index error

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

fixes: #58

### CODE REVIEW

**Comment by hferentschik** [comment]
Nice one. Definitely better.

**Comment by hferentschik** [comment]
I think the tests in `test_spec.sh` needs updating as well:

```
  2) AWS Storage The Reports bucket should be created
     call s3 [ "reports-tf-pr-59-1-20200525082147928400000007", ]
     2.1) [WARNING] It was exits with status non-zero but not found expectation
            status: 252
            
          # spec/test_spec.sh:68
     2.2) [WARNING] It was output to stderr but not found expectation
            stderr: 
            Parameter validation failed:
            Invalid bucket name "[": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
            
          # spec/test_spec.sh:68
  3) AWS Storage The Repository bucket should be created
     call s3 [ "repository-tf-pr-59-1-20200525082147900200000002", ]
     3.1) [WARNING] It was exits with status non-zero but not found expectation
            status: 252
            
          # spec/test_spec.sh:72
     3.2) [WARNING] It was output to stderr but not found expectation
            stderr: 
            Parameter validation failed:
            Invalid bucket name "[": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
            
          # spec/test_spec.sh:72
Finished in 26.60 seconds (user 15.67 seconds, sys 5.06 seconds)
18 examples, 0 failures, 3 warnings
```

**Comment by ankitm123** [comment]
I see, will do.

**Comment by ankitm123** [comment]
The tests are fine, I changed the output from string to tuple, but did not have the checks for the buckets, so the tests complained when they encountered a tuple. Should be good now @hferentschik

**Comment by hferentschik** [comment]
@ankitm123, seems you are really on fire ;-)

**Comment by ankitm123** [comment]
I deleted my jx namespace by mistake, when writing some tests for `jx diagnose`, and then thought about doing a terraform destroy, and saw some issues 😄

**Pull request merged**
