### PR TITLE
fix: fix issues with helm charts and upgrade versions

### LINKED ISSUE #233: JX3 setup failing. Kubernetes cluster unreachable: invalid configuration.
### Summary 
JX3 setup failed on AWS

### Steps to reproduce the behavior
1. generate repo from https://github.com/jx3-gitops-repositories/jx3-terraform-eks/generate (commit https://github.com/jenkins-x/terraform-aws-eks-jx/tree/af1182fc3d07881af6a96a2335255ef7b0dce7f6)

2. generate repo from  https://github.com/jx3-gitops-repositories/jx3-eks-vault/generate
3. configure terraform variables 
4. execute: `terraform apply`

### Expected behavior
Boot job stated without errors.

### Actual behavior

```
module.eks-jx.module.cluster.module.iam_assumable_role_cluster_autoscaler.aws_iam_role_policy_attachment.custom[0]: Creating...
module.eks-jx.module.cluster.module.iam_assumable_role_pipeline_visualizer.aws_iam_role_policy_attachment.custom[0]: Creating...
module.eks-jx.module.cluster.module.iam_assumable_role_external_dns.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-external-dns-20210121104622556100000019]
module.eks-jx.module.cluster.module.iam_assumable_role_controllerbuild.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-build-ctrl-2021012110462263690000001a]
module.eks-jx.module.cluster.module.iam_assumable_role_cm_cainjector.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cert-manager-cert-manager-cainjector-2021012110462269650000001b]
module.eks-jx.module.cluster.module.iam_assumable_role_cluster_autoscaler.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cluster-autoscaler-cluster-autoscaler-2021012110462283150000001c]
module.eks-jx.module.cluster.module.iam_assumable_role_pipeline_visualizer.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-jx-pipelines-visualizer-2021012110462286320000001d]
module.eks-jx.module.cluster.module.iam_assumable_role_tekton_bot.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-tekton-bot-2021012110462288510000001f]
module.eks-jx.module.cluster.module.iam_assumable_role_cert_manager.aws_iam_role_policy_attachment.custom[0]: Creation complete after 1s [id=jx-test-cert-manager-cert-manager-2021012110462288200000001e]
module.eks-jx.module.cluster.null_resource.kubeconfig (local-exec): Updated context arn:aws:eks:eu-central-1:xxx:cluster/jx-test in /Users/serhiykrupka/.kube/config
module.eks-jx.module.cluster.null_resource.kubeconfig: Creation complete after 1s [id=5757698152048227794]
module.eks-jx.module.cluster.helm_release.jx-git-operator[0]: Creating...

Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable



Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### Terraform version

```
v0.13.3
```

### Operating system

MacOS 11.1

### PR DESCRIPTION
**Pull request by ankitm123**
#### Description
* Add a helm provider and use updated token after cluster creation
* Update provider versions
* Update internal module versions

#### Which issue this PR fixes
fixes #233

### CODE REVIEW

**Comment by ankitm123** [comment]
I suppose it might be failing the fmt checks, which version of terraform does the image have? I tested mine with 0.14.6

**Comment by jstrachan** [comment]
current failure: 
```
Error: Unsupported Terraform Core version

  on .terraform/modules/cluster.eks/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.9, != 0.13.0"

Module module.cluster.module.eks (from terraform-aws-modules/eks/aws) does not
support Terraform version 0.13.0. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
```

FWIW I've created an image for running the tests inside & had issues if I tried 0.14.6 and 0.14.2 - found 0.13.0 was the only terraform version I tried that actually worked. What version works for you?
https://github.com/jenkins-x-images/terraform-aws-cli

**Comment by ankitm123** [comment]
I just tested locally with 0.14.6, can you create an image with that version of terraform, I can see why it's failing - I did see the tags issue - this PR should fix that as well.

**Comment by jstrachan** [comment]
now I get
```
Error: Unsupported argument

  on main.tf line 143, in module "health":
 143:   cluster_name         = local.cluster_name

An argument named "cluster_name" is not expected here.
```

**Comment by jstrachan** [comment]
@ankitm123 looking better so far - its past the linting... the actual CI test takes quite a while...

**Comment by jstrachan** [comment]
new error:
```
    terraform_eks_test.go:44:
        	Error Trace:	terraform_eks_test.go:44
        	Error:      	Received unexpected error:
        	            	InvalidParameterException: The name parameter contains invalid characters. It should begin with letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.
        	            	{
        	            	  RespMetadata: {
        	            	    StatusCode: 400,
        	            	    RequestID: "3221aaeb-ad8a-4fe1-a5b5-d17c5c7bf223"
        	            	  },
        	            	  ClusterName: "\"tf-jx-promoted-basilisk\"",
        	            	  Message_: "The name parameter contains invalid characters. It should begin with letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores."
        	            	}
        	Test:       	TestTerraformEksJX
TestTerraformEksJX 2021-02-15T05:01:36Z retry.go:72: terraform [output -no-color lts_logs_bucket]
    s3.go:316:
        	Error Trace:	s3.go:316
        	            				terraform_eks_test.go:48
        	Error:      	Received unexpected error:
        	            	BadRequest: Bad Request
        	            		status code: 400, request id: 0B9ABD5A81590C39, host id: 9S9FvbgWLwLuycGY6Tpf+H9apbU9KkHkOdSm9091V9tYl4R/8b9qNFvVxAhnRt8hjnpQBZmwmKQ=
        	Test:       	TestTerraformEksJX
```

**Comment by jstrachan** [comment]
now its...
```
    terraform_eks_test.go:50:
        	Error Trace:	terraform_eks_test.go:50
        	Error:      	Received unexpected error:
        	            	operation error EKS: DescribeCluster, https response error StatusCode: 400, RequestID: 93cd3424-b94f-41cd-b56e-58ae01286dac, api error InvalidParameterException: The name parameter contains invalid characters. It should begin with letter or digit and can have any of the following characters: the set of Unicode letters, digits, hyphens and underscores.
        	Test:       	TestTerraformEksJX
TestTerraformEksJX 2021-02-15T06:21:25Z retry.go:72: terraform [output -no-color lts_logs_bucket]
    s3.go:316:
        	Error Trace:	s3.go:316
        	            				terraform_eks_test.go:54
        	Error:      	Received unexpected error:
        	            	BadRequest: Bad Request
        	            		status code: 400, request id: B991E6120D666D35, host id: xRBtTLmtcZUNClriBqLZmwmR1STtnlhPZXivjRB6XX6uuA8NYbF/8nmhqYE5HvhOd1Yr0Jjs5sM=
        	Test:       	TestTerraformEksJX
```

**Pull request merged**
