### PR TITLE
chore: fix typo

### PR DESCRIPTION
**Pull request by jdnrg**
typo
chore: fix typo

### CODE REVIEW

**Comment by ankitm123** [comment]
@jdnrg Need to update the PR title to follow semantic convention check.

**Comment by ankitm123** [comment]
I updated the PR title. Can you change the commit message:
execute these commands:
```
git commit --amend -m "chore: fix typo"
git push -f origin patch-1
```

**Comment by jdnrg** [comment]
this is too much work right now.

**Comment by ankitm123** [comment]
I can push the changes to ur branch, if you are ok with it. Without this change, the PR checks wont pass, and also we use commit message formats to auto update the versions of the module.

**Pull request closed without merging**
