### PR TITLE
feat: support for terraform 0.13

### LINKED ISSUE #120: Make the module compatible with v0.12 and 0.13
### Summary 
Terraform v0.13 is now [GA](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/).
Certain things need to be changed to guarantee compatibility with both versions.https://www.terraform.io/docs/configuration/provider-requirements.html#v0-12-compatible-provider-requirements

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Description
* This should maintain compatibility with v0.12 and v0.13. 
* Updated aws-vpc module to use aws provider v3

#### Which issue this PR fixes

fixes #120

### CODE REVIEW

**Comment by rawlingsj** [comment]
awesome - fwiw if you want to change the pipeline to use the 0.13.0 you can use `gcr.io/jenkinsxio/builder-terraform:0.0.0-SNAPSHOT-PR-1389-1`  https://github.com/jenkins-x/terraform-aws-eks-jx/blob/6e085c2d28dcfc3d4d4008c0c73c253b1f9805db/jenkins-x.yml#L13 

CI failed with this BTW
```
Showing logs for build jenkins-x-terraform-aws-eks-jx-m9qbr-1 stage ci and container step-terraform-lint
terraform init
Initializing modules...
- backup in modules/backup
- cluster in modules/cluster
Downloading terraform-aws-modules/eks/aws 12.1.0 for cluster.eks...
- cluster.eks in .terraform/modules/cluster.eks
- cluster.eks.node_groups in .terraform/modules/cluster.eks/modules/node_groups
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_cert_manager...
- cluster.iam_assumable_role_cert_manager in .terraform/modules/cluster.iam_assumable_role_cert_manager/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_cm_cainjector...
- cluster.iam_assumable_role_cm_cainjector in .terraform/modules/cluster.iam_assumable_role_cm_cainjector/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_controllerbuild...
- cluster.iam_assumable_role_controllerbuild in .terraform/modules/cluster.iam_assumable_role_controllerbuild/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_external_dns...
- cluster.iam_assumable_role_external_dns in .terraform/modules/cluster.iam_assumable_role_external_dns/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_**ui...
- cluster.iam_assumable_role_**ui in .terraform/modules/cluster.iam_assumable_role_**ui/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/iam/aws 2.13.0 for cluster.iam_assumable_role_tekton_bot...
- cluster.iam_assumable_role_tekton_bot in .terraform/modules/cluster.iam_assumable_role_tekton_bot/modules/iam-assumable-role-with-oidc
Downloading terraform-aws-modules/vpc/aws 2.46.0 for cluster.vpc...
- cluster.vpc in .terraform/modules/cluster.vpc
- dns in modules/dns
- vault in modules/vault
Error: Unsupported Terraform Core version
This configuration does not support Terraform version 0.12.17. To proceed,
either choose another supported Terraform version or update the root module's
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
make: *** [init] Error 1

```

**Comment by ankitm123** [comment]
So, the issue with the pr-build was that I had set the minimum version of terraform to 0.12.26, changed it to 0.12.17, which is what the builder image has (I have a ticket to clean up that ).
I will change the image to the 0.13 one, and run a PR build (to check, if it works or not).

**Pull request merged**
