### PR TITLE
chore: change aws creds mount path

### LINKED ISSUE #116: PR checks are broken
### Summary 
PR checks are broken after the recent tekton upgrade. Relevant PR: https://github.com/jenkins-x/jx/pull/7460

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Description
This PR fixes the issue with broken PR checks:
```
Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider
  on main.tf line 12, in provider "aws":
  12: provider "aws" {
```

#### Which issue this PR fixes

fixes #116

### CODE REVIEW

**Comment by rawlingsj** [comment]
Great! Not too sure if there is a standard formatted that should be used but I can see the change to switch the tekton home dir. 

/lgtm

**Comment by ankitm123** [comment]
I need to take a look at that terraform lint checks we have, seems like it is not catching things @rawlingsj

**Pull request merged**
