### PR TITLE
feat(backup): velero storage and IAM

### LINKED ISSUE #17: Setup Velero backups
Similar to the GKE module there should be a Velero backup configuration. At the very least it should be possible to optionally enable it. If enabled the Velero storage bucket needs to be created.

### PR DESCRIPTION
**Pull request by patrickleet**
#### Description

Create required resources for Velero when `enable_backup` is `true`.

```
module "eks-jx" {
  source  = "jenkins-x/eks-jx/aws"
  enable_backup = true
}
```

#### Which issue this PR fixes

fixes #17

### CODE REVIEW

**Comment by patrickleet** [comment]
The part that I am not clear about is `credentials-velero` secret - not sure what key name it expects:
https://hub.helm.sh/charts/vmware-tanzu/velero

**Comment by patrickleet** [comment]
Related PR: https://github.com/jenkins-x/jenkins-x-versions/pull/1010

**Comment by patrickleet** [comment]
In a GKE cluster the key is "cloud", so .. maybe it's the same in AWS?

```
apiVersion: v1
data:
  cloud: XXX==
kind: Secret
metadata:
  creationTimestamp: "2020-03-11T02:57:39Z"
  labels:
    component: velero
  name: velero-secret
  namespace: velero
  resourceVersion: "1668"
  selfLink: /api/v1/namespaces/velero/secrets/velero-secret
  uid: 77ec3a98-c735-48e4-afab-c74ee320c9a6
type: Opaque
```

**Comment by patrickleet** [comment]
Woot! This is working on my cluster:

```
> velero get backups

NAME                            STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
default-backup-20200708201524   Completed   2020-07-08 16:15:24 -0400 EDT   29d       default            <none>
```

**Comment by joebertj** [comment]
On an existing installation I get this:

`Error: namespaces "velero" already exists`

I need to delete the namespace manually first.

**Comment by patrickleet** [comment]
I am trying to google and find a workaround for that.. Should we tell people to import first if it's an existing cluster? Why does the velero ns exist when backups were previously not enabled?

something like this maybe? https://github.com/hashicorp/terraform-provider-kubernetes/issues/613#issuecomment-559473848

**Comment by patrickleet** [comment]
```
terraform import kubernetes_namespace.velero_namespace velero
```

**Comment by joebertj** [comment]
```
$ velero get backups
NAME                            STATUS                      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
default-backup-20200710030053   PartiallyFailed (1 error)   2020-07-10 11:00:53 +0800 PST   29d       default            <none>
default-backup-20200710024450   PartiallyFailed (1 error)   2020-07-10 10:44:50 +0800 PST   29d       default            <none>
```

**Comment by patrickleet** [comment]
what's the error - looks like velero is running - that could be specific to your cluster - like if you had apiservices that aren't responding or crds that were added then removed I've seen velero act up

**Comment by patrickleet** [comment]
fwiw I also have pending PRs to try to get velero upgraded as we are using a deprecated chart - this tf part works the same for both though 

https://github.com/jenkins-x/jenkins-x-versions/pull/1010
https://github.com/jenkins-x/jenkins-x-boot-config/pull/171

**Comment by joebertj** [comment]
i'll dig deeper later. just trying to test this PR.

**Comment by patrickleet** [comment]
from what you posted it looks like it's working despite the "PartiallyFailed" is my point - it means a resource in your cluster couldn't be backed up vs. a complete Failure

**Comment by joebertj** [comment]
so this is the issus:

` error="clusterroles.rbac.authorization.k8s.io \"cm-cert-manager-leaderelection\" not found"`

**Comment by patrickleet** [comment]
right, so nothing to do velero itself running/working - that's something on your cluster specifically.

I have an old cluster on GKE that also has this error.

**Comment by patrickleet** [comment]
it's because you have a service account that references that clusterrole, and that clusterrole doesn't exist

**Comment by patrickleet** [comment]
Run these command to see:

```
> kubectl get clusterrolebinding cm-cert-manager-leaderelection -o yaml

// ...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cm-cert-manager-leaderelection
```

```
> kubectl get clusterrole cm-cert-manager-leaderelection                                      
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "cm-cert-manager-leaderelection" not found
```

**Comment by ankitm123** [comment]
> I am trying to google and find a workaround for that.. Should we tell people to import first if it's an existing cluster? Why does the velero ns exist when backups were previously not enabled?

I think conditional creation would be better, so if the ns exists, do not create it. wdyt?

**Comment by patrickleet** [comment]
That's more likely to cert-manager chart being almost a year old:
https://github.com/jenkins-x/jenkins-x-versions/blob/master/charts/stable/cert-manager.yml
https://hub.helm.sh/charts/jetstack/cert-manager

**Comment by patrickleet** [comment]
> I think conditional creation would be better, so if the ns exists, do not create it. wdyt?

It seems the recommended approach is importing:

> the preferred / recommended way to approach this problem is to actually import the existing resource into Terraform if in fact it will at any point be managed / created by Terraform.
>
> The datasource approach should only be used for inspecting resources that will never be managed by TF.

https://github.com/hashicorp/terraform-provider-kubernetes/issues/613#issuecomment-559504177

**Comment by patrickleet** [comment]
I'm guessing `jx boot` creates the velero namespace even though it isn't actually used?

**Comment by patrickleet** [comment]
Probably these steps: https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/jenkins-x.yml#L77-L106

**Comment by ankitm123** [comment]
> I'm guessing `jx boot` creates the velero namespace even though it isn't actually used?

What I am more concerned about is, once you import it into terraform, tf is going to manage the lifecycle, so a `terraform destroy` will also delete it. This is fine, if it was created for new clusters, but could be an issue for existing clusters. Same with creating an iam user specifically for velero (and even vault...). 
I have not looked into the gcp terraform module. but I guess it does what you are implementing here, right?

**Comment by patrickleet** [comment]
I believe so - I haven't actually used the jx-gcp terraform module - I've been using Terraform with GKE/JX since before that existed with this: https://github.com/CloudNativeEntrepreneur/infrastructure/blob/master/velero.tf

That being said, I did look at the google-jx terraform module to try to make it similar.

In the case where someone didn't want to use this backup module because they are already using velero, they could set `enable_backups` to false

**Comment by patrickleet** [comment]
>tf is going to manage the lifecycle, so a terraform destroy will also delete it.

We could add 
```
  lifecycle {
    prevent_destroy = true
  }
```

**Comment by ankitm123** [comment]
I will give it a try, and come back to you (A good weekend activity :))

**Comment by patrickleet** [comment]
tbh, it seems like something that just documenting in the README could resolve.

Users should be able to upgrade the version and apply without issue as the default value is/was `false` for `enable_backups`.

If they then turn on `enable_backups` and have a cluster with velero already in it, they get an error as a warning. They then adjust accordingly by importing, or deleting the previously existing ns.

**Comment by patrickleet** [comment]
This has been discussed here as well: https://github.com/jenkins-x/terraform-google-jx/issues/82

**Comment by patrickleet** [comment]
Re: this "workaround" - hashicorp/terraform-provider-kubernetes#613 (comment)

Trying to use the kubernetes_namespace data source gets weird. 

First off, it's in a newer version of the kubernetes provider - only released in latest version - so bumping to `1.11.3` from `1.11.1` enables it.

We basically then have the opposite problem.

Terraform creates ns if you've enabled backups and it isn't already there.

Then the next time you run, all that logic based on whether or not it already exists starts kicking in, so terraform then tries to unmanage it - basically it just flip flops back and forth. It seems like we would have to also keep track of what the initial state was to be able to factor that into the decision making - and at this point I say... Let's just put a note in the README saying this: https://github.com/jenkins-x/terraform-aws-eks-jx/pull/109#issuecomment-656670325

```
data "kubernetes_namespace" "velero" {
  metadata {
    name = var.velero_namespace
  }
}


// namespaceDoesNotExist = lookup(data.kubernetes_namespace.velero, "id") == null
// count = enable_backup ? (namespaceDoesNotExist ? 1 : 0) : 0
resource "kubernetes_namespace" "velero" {
  count         = var.enable_backup ? (lookup(data.kubernetes_namespace.velero, "id") == null ? 1 : 0) : 0

  metadata {
    name = var.velero_namespace
  }

  lifecycle {
    ignore_changes = [
      metadata[0].labels,
      metadata[0].annotations,
    ]
  }
}

```

**Comment by patrickleet** [comment]
Added a section to the README explaining how to import an existing velero namespace

**Comment by joebertj** [comment]
```
$ kubectl get clusterrolebinding cm-cert-manager-leaderelection -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    jenkins.io/chart: cm
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"ClusterRoleBinding","metadata":{"annotations":{"jenkins.io/chart":"cm"},"labels":{"app":"cert-manager","app.kubernetes.io/instance":"cm","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"cert-manager","helm.sh/chart":"cert-manager-v0.11.0","jenkins.io/chart-release":"cm","jenkins.io/version":"1"},"name":"cm-cert-manager-leaderelection"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cm-cert-manager-leaderelection"},"subjects":[{"kind":"ServiceAccount","name":"cm-cert-manager","namespace":"cert-manager"}]}
  creationTimestamp: "2020-06-03T08:09:57Z"
  labels:
    app: cert-manager
    app.kubernetes.io/instance: cm
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cert-manager
    helm.sh/chart: cert-manager-v0.11.0
    jenkins.io/chart-release: cm
    jenkins.io/version: "1"
  name: cm-cert-manager-leaderelection
  resourceVersion: "628877"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/cm-cert-manager-leaderelection
  uid: 068243cf-f2e8-4b57-b4cc-28cf818a4543
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cm-cert-manager-leaderelection
subjects:
- kind: ServiceAccount
  name: cm-cert-manager
  namespace: cert-manager

**Comment by patrickleet** [comment]
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: cm-cert-manager-leaderelection

yes... like i said here: https://github.com/jenkins-x/terraform-aws-eks-jx/pull/109#issuecomment-656656781

**Comment by rawlingsj** [comment]
I'm not too familiar with Terraform and practices around it.  @garethjevans / @cagiti / @dgozalo / @ankitm123 I know are busy but might be able to give a review and if good we can approve?

**Comment by ankitm123** [comment]
@patrickleet there are some linting issues (we were not running terraform fmt with recursive flag, so the files inside sub-directories never got linted). You just need to rebase, and then run `make lint`.

**Comment by patrickleet** [comment]
Ok I'll do that later when I'm on my computer

**Comment by patrickleet** [comment]
ok - done!

`make lint` just checks btw, it doesn't actually apply the formatting

**Comment by patrickleet** [comment]
@ankitm123 ^ forgot to tag you

**Comment by ankitm123** [comment]
Right, it just checks, then you can fix them :smile:

**Pull request merged**
